version: '3.9'

services:
  fastapi:
    container_name: "fastapi_container"
    build:
      context: ..
      dockerfile: docker_pro/fastapi.Dockerfile
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - ASGI_SERVER=uvicorn
      - UVICORN_CMD="uvicorn main:app --host 0.0.0.0 --port 80 --workers 4"
      - GUNICORN_CMD="gunicorn -k uvicorn.workers.UvicornWorker -w 4 main:app -b 0.0.0.0:80"
    restart: always

  postgres:
    build:
      context: ..
      dockerfile: docker_pro/postgres.Dockerfile
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    build:
      context: ..
      dockerfile: docker_pro/pgAdmin.Dockerfile
    container_name: pgadmin_container
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx:
    build:
      context: ..
      dockerfile: docker_pro/nginx.Dockerfile
    container_name: nginx_container
    ports:
      # Port FastAPI
      - "8000:80"
      # Port Postgresql
      - "5454:5454"
      # Port pgAdmin
      - "5050:5050"
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
  nginx_data:

